#Data Preprocessing

##Importing Libraries and Dataset

In [28]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [29]:
data=pd.read_csv("Data1.csv")
x=data.iloc[:,1:-1].values
y=data.iloc[:,-1].values

In [30]:
print(x)

[['Male' 35.0 20000.0]
 ['Male' 40.0 43500.0]
 ['Male' 49.0 74000.0]
 ...
 ['Female' 28.0 138500.0]
 ['Female' 48.0 134000.0]
 ['Female' 44.0 73500.0]]


In [31]:
print(y)

['No' 'No' 'No' 'Yes' 'No' 'Yes' 'Yes' 'No' 'No' 'No' 'No' 'Yes' 'No' 'No'
 'Yes' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'Yes' 'No' 'No' 'No' 'Yes'
 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'No' 'No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No'
 'No' 'Yes' 'No' 'No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'Yes' 'Yes'
 'No' 'Yes' 'Yes' 'Yes' 'No' 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'No' 'No'
 'No' 'Yes' 'No' 'No' 'No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'No' 'Yes'
 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'No' 'No' 'No' 'No' 'Yes'
 'No' 'No' 'Yes' 'Yes' 'Yes' 'No' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No'
 'Yes' 'No' 'Yes' 'No' 'Yes' 'Yes' 'No' 'No' 'No' 'Yes' 'No' 'Yes' 'Yes'
 'No' 'No' 'Yes' 'Yes' 'No' 'No' 'No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No'
 'No' 'Yes' 'No' 'No' 'No' 'No' 'Yes' 'No' 'Yes' 'No' 'No' 'Yes' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'Yes' 'Yes' 'Yes' 'No' 'Yes' 'No'
 'No' 'Yes' 'Yes' 'Yes' 'No' 'Yes' 'Yes' 'No' 'No' 'Yes' 'No' 'No' 'Yes'
 'No' 'No' 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes'

##Handling the Missing data

In [32]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy="mean")
imputer.fit(x[:,1:])
x[:,1:]=imputer.transform(x[:,1:])

In [33]:
print(x)

[['Male' 35.0 20000.0]
 ['Male' 40.0 43500.0]
 ['Male' 49.0 74000.0]
 ...
 ['Female' 28.0 138500.0]
 ['Female' 48.0 134000.0]
 ['Female' 44.0 73500.0]]


##Encoding the Data

In [34]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[("encoder",OneHotEncoder(),[0])],remainder="passthrough")
x=np.array(ct.fit_transform(x))

In [35]:
print(x)

[[0.0 1.0 0.0 35.0 20000.0]
 [0.0 1.0 0.0 40.0 43500.0]
 [0.0 1.0 0.0 49.0 74000.0]
 ...
 [1.0 0.0 0.0 28.0 138500.0]
 [1.0 0.0 0.0 48.0 134000.0]
 [1.0 0.0 0.0 44.0 73500.0]]


In [36]:
from sklearn.preprocessing import LabelEncoder
l=LabelEncoder()
y=l.fit_transform(y)

In [37]:
print(y)

[0 0 0 1 0 1 1 0 0 0 0 1 0 0 1 1 0 0 1 1 0 1 1 0 0 0 1 1 1 1 1 0 0 0 1 0 0
 1 1 0 0 1 0 0 1 0 0 1 1 0 1 1 1 0 1 1 1 0 0 1 1 1 1 0 0 0 0 1 0 0 0 1 0 0
 1 1 0 0 1 1 1 1 1 0 1 1 1 0 0 0 0 1 0 0 1 1 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1
 0 0 0 1 0 1 1 0 0 1 1 0 0 0 1 0 0 1 1 0 0 1 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0
 0 0 0 0 0 1 1 1 0 1 0 0 1 1 1 0 1 1 0 0 1 0 0 1 0 0 1 0 1 1 1 1 1 0 0 1 1
 1 1 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 1 1 1 1 0 0 0 0 1 1 0 0 0 0
 0 0 0 0 1 1 0 0 0 0 1 0 1 1 1 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 0 1 0 1 0 0
 0 0 0 0 1 1 1 0 1 0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 1 1 0 1 0 1 0 0 1 1 0 0 0
 0 1 1 1 1 0 0 0 1 1 1 0 0 0 0 1 1 0 1 1 0 1 0 0 0 1 0 1 0 0 0 0 0 0 0 1 0
 0 1 0 1 0 1 0 0 0 1 0 0 1 0 1 1 1 1 1 0 0 0 1 0 1 1 0 1 0 0 1 1 1 0 0 0 0
 1 1 0 0 0 0 1 0 1 1 0 1 0 0 0 1 1 0 0 1 0 0 1 1 0 0 1 0 0 1 0 0 0 1 0 0 0
 0 0 1 1 0 1 0 0 1 1 1 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 0 1 1 0 0 0 1 0 0 1
 0 1 0 0 0 0 1 1 0 1 0 0 1 1 1 0 0 0 0 1 0 0 0 0 1 1 0 1 0 1 1 1 0 0 1 0 1
 0 0 0 0 1 0 1 1 1 0 0 1 

##Splitting the Test and Train data

In [38]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [44]:
print(x_train)

[[0.0 1.0 0.0 -2.00241941373311 -0.0950448943315108]
 [1.0 0.0 0.0 1.2039769896196895 0.8747859503183579]
 [0.0 1.0 0.0 -0.11630388234911032 -0.366027042101327]
 ...
 [0.0 1.0 0.0 -0.39922121205671024 -0.5371736617454216]
 [1.0 0.0 0.0 -0.02199810577991033 0.09036394361625823]
 [1.0 0.0 0.0 -0.11630388234911032 1.1742925346955233]]


In [40]:
print(x_test)

[[1.0 0.0 0.0 30.0 79000.0]
 [1.0 0.0 0.0 38.0 79500.0]
 [0.0 1.0 0.0 43.0 77500.0]
 [1.0 0.0 0.0 42.0 73500.0]
 [0.0 1.0 0.0 36.0 92500.0]
 [0.0 1.0 0.0 43.0 72690.21190716448]
 [0.0 1.0 0.0 42.0 65000.0]
 [0.0 1.0 0.0 43.0 65500.0]
 [0.0 1.0 0.0 36.0 73500.0]
 [1.0 0.0 0.0 40.0 60500.0]
 [0.0 1.0 0.0 26.0 32000.0]
 [0.0 1.0 0.0 57.0 72500.0]
 [0.0 1.0 0.0 19.0 83500.0]
 [0.0 1.0 0.0 39.0 106000.0]
 [1.0 0.0 0.0 36.0 48500.0]
 [1.0 0.0 0.0 36.0 75000.0]
 [0.0 1.0 0.0 26.0 16000.0]
 [1.0 0.0 0.0 46.0 132500.0]
 [1.0 0.0 0.0 22.0 27000.0]
 [0.0 1.0 0.0 47.0 80500.0]
 [0.0 1.0 0.0 42.0 53500.0]
 [1.0 0.0 0.0 41.0 51000.0]
 [1.0 0.0 0.0 37.0 80000.0]
 [0.0 1.0 0.0 32.0 18000.0]
 [1.0 0.0 0.0 21.0 68000.0]
 [0.0 1.0 0.0 28.0 59000.0]
 [1.0 0.0 0.0 18.0 44000.0]
 [0.0 1.0 0.0 33.0 31000.0]
 [0.0 1.0 0.0 40.0 61000.0]
 [1.0 0.0 0.0 29.0 56500.0]
 [0.0 1.0 0.0 48.0 35500.0]
 [0.0 1.0 0.0 35.0 73000.0]
 [1.0 0.0 0.0 40.0 142000.0]
 [0.0 1.0 0.0 41.0 108500.0]
 [1.0 0.0 0.0 30.0 116000.0]
 [1.0

##Feature Scaling

In [41]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train[:,3:] =sc.fit_transform(x_train[:,3:])
x_test[:,3:] =sc.transform(x_test[:,3:])

In [42]:
print(x_train)

[[0.0 1.0 0.0 -2.00241941373311 -0.0950448943315108]
 [1.0 0.0 0.0 1.2039769896196895 0.8747859503183579]
 [0.0 1.0 0.0 -0.11630388234911032 -0.366027042101327]
 ...
 [0.0 1.0 0.0 -0.39922121205671024 -0.5371736617454216]
 [1.0 0.0 0.0 -0.02199810577991033 0.09036394361625823]
 [1.0 0.0 0.0 -0.11630388234911032 1.1742925346955233]]


In [43]:
print(x_test)

[[1.0 0.0 0.0 -0.9650558714719102 0.16167503513463094]
 [1.0 0.0 0.0 -0.2106096589183103 0.17593725343830546]
 [0.0 1.0 0.0 0.2609192239276896 0.11888838022360732]
 [1.0 0.0 0.0 0.16661344735848962 0.004790633794210989]
 [0.0 1.0 0.0 -0.39922121205671024 0.5467549293338435]
 [0.0 1.0 0.0 0.2609192239276896 -0.01830811532526178]
 [0.0 1.0 0.0 0.16661344735848962 -0.23766707736825618]
 [0.0 1.0 0.0 0.2609192239276896 -0.22340485906458166]
 [0.0 1.0 0.0 -0.39922121205671024 0.004790633794210989]
 [1.0 0.0 0.0 -0.02199810577991033 -0.366027042101327]
 [0.0 1.0 0.0 -1.34227897774871 -1.1789734854107758]
 [0.0 1.0 0.0 1.5812000958964894 -0.02373380281313809]
 [0.0 1.0 0.0 -2.00241941373311 0.2900349998677018]
 [0.0 1.0 0.0 -0.11630388234911032 0.9318348235330561]
 [1.0 0.0 0.0 -0.39922121205671024 -0.708320281389516]
 [1.0 0.0 0.0 -0.39922121205671024 0.04757728870523461]
 [0.0 1.0 0.0 -1.34227897774871 -1.635364471128361]
 [1.0 0.0 0.0 0.5438365536352896 1.6877323936278068]
 [1.0 0.0 0.0 -1